server:
    AppVersion: 1.0.0
    Mode: Development
    ReadTimeout: 5
    WriteTimeout: 5
    SSL: false
    CtxDefaultTimeout: 12
    Debug: true

postgreSQL:
    Host: arjuna.db.elephantsql.com
    Port: 5432
    User: yvcdxyzf
    Password: 1galqec--Jgc41gI9pNr6IrP36_CCNVD
    DBName: yvcdxyzf

redis:
    Host: go-clean-arch.redis.cache.windows.net
    Port: 6380
    DB: 0
    Username:
    Password: CQHM8v91MKO6lR8Kc647AFG8yUvvjbarWAzCaFsFMxE=
    PoolSize: 10
    PoolTimeout: 60

auth:
    JWTSecret: initiaRe_secret_key
    Expire: 3600
    Issuer: initiaRe_server
    Audience: initiaRe_client
