server:
  AppVersion: 1.0.0
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: false
  CtxDefaultTimeout: 12
  Port: 5001
  SuperAdmin: admin_user@initiare

logger:
  Level: debug
  Mode: pretty
  # Format: text
  # Output: stdout

postgreSQL:
  Host: postgres
  Port: 5432
  User: postgres
  Password: password
  DBName: initiare
  SSL: False
  # User: Minhho
  # Password: 26082005Hm

redis:
  Host: redis
  Port: 6379
  DB: 0

auth:
  Secret: initiaRe_secret_key
  Expire: 3600
  Issuer: initiaRe_server
  Audience: initiaRe_client

storage:
  Host: https://initiarestorage.blob.core.windows.net/
  Container: media
  AccountName: initiarestorage
  AccountKey: Fuidf6AR7/aZCcwg42lEYHSAc8rb1b+5zShggFmHl61Wl76Wc4iFFM1+MtNtUU9tYcjrRQBkFAjO+AStkI7uBg==
