server:
    AppVersion: 1.0.0
    Mode: Development
    ReadTimeout: 5
    WriteTimeout: 5
    SSL: false
    CtxDefaultTimeout: 12
    Debug: true

postgreSQL:
    Host: arjuna.db.elephantsql.com
    Port: 5432
    User: yvcdxyzf
    Password: 1galqec--Jgc41gI9pNr6IrP36_CCNVD
    DBName: yvcdxyzf

redis:
    Host: redis-14027.c1.ap-southeast-1-1.ec2.cloud.redislabs.com
    Port: 14027
    DB: 0
    Username: default
    Password: gb1ad1PWZbkAPWwrsbLScNNUmGYWtXNI
    PoolSize: 10
    PoolTimeout: 60

auth:
    JWTSecret: initiaRe_secret_key
    Expire: 3600
    Issuer: initiaRe_server
    Audience: initiaRe_client
