package constant

const (
	ARTICLE_STATUS_PENDING int = iota + 1
	ARTICLE_STATUS_APPROVED
	ARTICLE_STATUS_HIDDEN
)

var ARTICLE_STATUS = map[int]string{
	ARTICLE_STATUS_PENDING:  "Pending",
	ARTICLE_STATUS_APPROVED: "Approved",
	ARTICLE_STATUS_HIDDEN:   "Hidden",
}

const (
	ARTICLE_TYPE_RESEARCH_PAPER int = iota + 1
	ARTICLE_TYPE_REVIEW_PAPER
	ARTICLE_TYPE_RESEARCH_PROPOSAL
	ARTICLE_TYPE_POSTER
	ARTICLE_TYPE_ABSTRACT
)

var ARTICLE_TYPE = map[int]string{
	ARTICLE_TYPE_RESEARCH_PAPER:    "Research Paper",
	ARTICLE_TYPE_REVIEW_PAPER:      "Review Paper",
	ARTICLE_TYPE_RESEARCH_PROPOSAL: "Research Proposal",
	ARTICLE_TYPE_POSTER:            "Poster",
	ARTICLE_TYPE_ABSTRACT:          "Abstract",
}
