basePath: /api/v1
definitions:
  github_com_Ho-Minh_InitiaRe-website_internal_article_models.CreateRequest:
    properties:
      content:
        type: string
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_article_models.ListPaging:
    properties:
      page:
        type: integer
      records:
        items:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_article_models.Response'
        type: array
      size:
        type: integer
      total:
        type: integer
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_article_models.Response:
    properties:
      category_id:
        type: integer
      content:
        type: string
      created_at:
        type: string
      created_by:
        type: integer
      id:
        type: integer
      publish_date:
        type: string
      status_id:
        type: integer
      updated_at:
        type: string
      updated_by:
        type: integer
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_article_models.UpdateRequest:
    properties:
      category_id:
        type: integer
      content:
        type: string
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_auth_models.Response:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      last_name:
        type: string
      school:
        type: string
      user_id:
        type: string
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_category_models.CreateRequest:
    properties:
      category:
        type: string
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_category_models.ListPaging:
    properties:
      page:
        type: integer
      records:
        items:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_category_models.Response'
        type: array
      size:
        type: integer
      total:
        type: integer
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_category_models.Response:
    properties:
      category:
        type: string
      created_at:
        type: string
      created_by:
        type: integer
      id:
        type: integer
      updated_at:
        type: string
      updated_by:
        type: integer
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_category_models.UpdateRequest:
    properties:
      category:
        type: string
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_storage_models.Response:
    properties:
      created_at:
        type: string
      created_by:
        type: integer
      download_url:
        type: string
      id:
        type: integer
      type:
        type: string
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_todo_models.CreateRequest:
    properties:
      content:
        type: string
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_todo_models.ListPaging:
    properties:
      page:
        type: integer
      records:
        items:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.Response'
        type: array
      size:
        type: integer
      total:
        type: integer
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_todo_models.Response:
    properties:
      content:
        type: string
      created_at:
        type: string
      created_by:
        type: integer
      id:
        type: integer
      update_by:
        type: integer
      updated_at:
        type: string
    type: object
  github_com_Ho-Minh_InitiaRe-website_internal_todo_models.UpdateRequest:
    properties:
      content:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
      password:
        type: string
      school:
        type: string
    type: object
  models.UserWithToken:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_auth_models.Response'
    type: object
info:
  contact:
    email: email@here.com
    name: Someone here
    url: contact.here
  description: InitiaRe REST API.
  title: InitiaRe API
  version: "1.0"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Get list article with paging and filter
      parameters:
      - description: Page
        in: query
        name: Page
        required: true
        type: integer
      - description: Size
        in: query
        name: Size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_article_models.ListPaging'
      summary: Get list article
      tags:
      - Article
    post:
      consumes:
      - application/json
      description: Create new article
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_article_models.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_article_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Create article
      tags:
      - Article
  /articles/{id}:
    put:
      consumes:
      - application/json
      description: Update an existing article
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_article_models.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_article_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Update article
      tags:
      - Article
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login and return token
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserWithToken'
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create new user, returns user and token
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_auth_models.Response'
      summary: Create new user
      tags:
      - Auth
  /categories:
    get:
      consumes:
      - application/json
      description: Get list category with paging and filter
      parameters:
      - description: Page
        in: query
        name: Page
        required: true
        type: integer
      - description: Size
        in: query
        name: Size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_category_models.ListPaging'
      security:
      - ApiKeyAuth: []
      summary: Get list category
      tags:
      - Category
    post:
      consumes:
      - application/json
      description: Create new category
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_category_models.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_category_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Create category
      tags:
      - Category
  /categories/{id}:
    put:
      consumes:
      - application/json
      description: Update category
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_category_models.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_category_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Update category
      tags:
      - Category
  /storage/media/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload media file (pdf, docs, images, videos, etc.)
      parameters:
      - description: binary file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_storage_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Upload media
      tags:
      - Storage
  /todos:
    get:
      description: Get list todo with paging and filter
      parameters:
      - description: Page
        in: query
        name: Page
        required: true
        type: integer
      - description: Size
        in: query
        name: Size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.ListPaging'
      security:
      - ApiKeyAuth: []
      summary: Get list todo
      tags:
      - Todo
    post:
      consumes:
      - application/json
      description: Create new todo
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Create todo
      tags:
      - Todo
  /todos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete todo
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete todo
      tags:
      - Todo
    get:
      description: Get detail todo
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Get detail todo
      tags:
      - Todo
    put:
      consumes:
      - application/json
      description: Update todo
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Update todo
      tags:
      - Todo
  /todos/me:
    get:
      description: Get list current user todo by token
      parameters:
      - description: Page
        in: query
        name: Page
        required: true
        type: integer
      - description: Size
        in: query
        name: Size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_todo_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Get list current user todo
      tags:
      - Todo
  /users/me:
    get:
      description: Get user info by token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ho-Minh_InitiaRe-website_internal_auth_models.Response'
      security:
      - ApiKeyAuth: []
      summary: Get user info
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
